/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '07/11/16 11:11' with Gradle 3.1
 *
 * @author luisb, @date 07/11/16 11:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
